import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.ai": "AI Capabilities",
    "nav.erpnext": "ERPNext",
    "nav.contact": "Contact",
    "nav.getStarted": "Get Started",

    // Hero
    "hero.badge": "AI-Powered Solutions",
    "hero.title1": "Smart Digital Transformation",
    "hero.title2": "Powered by AI",
    "hero.title3": "& ERPNext",
    "hero.description": "Empower your business with cutting-edge AI automation, comprehensive ERP solutions, and data-driven decision making. Transform the way you work.",
    "hero.cta1": "Book a Free Consultation",
    "hero.cta2": "Request a Demo",
    "hero.trusted": "Trusted by leading companies across industries",

    // Industries
    "industry.manufacturing": "Manufacturing",
    "industry.retail": "Retail",
    "industry.logistics": "Logistics",
    "industry.services": "Services",

    // Services Section
    "services.label": "Our Services",
    "services.title1": "Comprehensive Solutions for",
    "services.title2": "Modern Businesses",
    "services.description": "From ERP implementation to AI-powered automation, we provide end-to-end solutions tailored to your business needs.",
    "services.learnMore": "Learn more",

    // Service Items
    "service.erp.title": "ERP Implementation",
    "service.erp.description": "Full ERPNext implementation covering Finance, HR, Inventory, Sales & Procurement with custom workflows.",
    "service.crm.title": "CRM Solutions",
    "service.crm.description": "AI-powered customer insights and sales pipeline automation for enhanced customer relationships.",
    "service.ai.title": "AI Automation",
    "service.ai.description": "Intelligent reporting, predictive analytics, and process automation using cutting-edge AI.",
    "service.digital.title": "Digital Transformation",
    "service.digital.description": "Business process re-engineering and cloud-based system modernization.",
    "service.governance.title": "Corporate Governance",
    "service.governance.description": "Policy automation and audit-ready ERP systems for compliance excellence.",
    "service.analytics.title": "Data Analytics",
    "service.analytics.description": "Transform raw data into actionable insights with AI-driven dashboards and reports.",

    // Why Amy Tech
    "why.label": "Why Amy Tech",
    "why.title1": "Your Trusted Partner for",
    "why.title2": "Digital Excellence",
    "why.description": "We combine deep industry expertise with cutting-edge AI technology to deliver solutions that drive real business results.",
    "why.item1": "Certified ERPNext implementation partners",
    "why.item2": "AI-first approach to all solutions",
    "why.item3": "24/7 dedicated support team",
    "why.item4": "Proven track record across industries",
    "why.item5": "Customized solutions for your needs",
    "why.learnMore": "Learn More About Us",

    // Feature Cards
    "feature.aiPowered": "AI-Powered",
    "feature.aiPowered.desc": "Smart automation and predictive analytics",
    "feature.erpnext": "ERPNext",
    "feature.erpnext.desc": "Complete business management system",
    "feature.secure": "Secure",
    "feature.secure.desc": "Enterprise-grade security & compliance",
    "feature.scalable": "Scalable",
    "feature.scalable.desc": "Grow without limitations",

    // CTA Section
    "cta.title": "Ready to Transform Your Business?",
    "cta.description": "Schedule a free consultation with our experts and discover how AI-powered solutions can revolutionize your operations.",
    "cta.button1": "Book Free Consultation",
    "cta.button2": "Explore Services",

    // Footer
    "footer.description": "Empowering businesses through AI-driven ERP & CRM solutions. Your trusted partner for digital transformation and corporate governance.",
    "footer.company": "Company",
    "footer.services": "Services",
    "footer.contact": "Contact Us",
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",

    // Language
    "lang.switch": "العربية",

    // About Page
    "about.badge": "About Us",
    "about.hero.title1": "Empowering Businesses Through",
    "about.hero.title2": "AI Innovation",
    "about.hero.description": "We are a technology startup dedicated to transforming businesses with AI-driven ERP, CRM solutions, and digital excellence.",
    "about.mission.title": "Our Mission",
    "about.mission.description": "To empower businesses through AI-driven ERP & CRM solutions, enabling them to achieve operational excellence, make data-driven decisions, and stay ahead in an ever-evolving digital landscape.",
    "about.vision.title": "Our Vision",
    "about.vision.description": "To become a leading digital transformation and corporate governance partner, recognized globally for our innovative AI solutions, exceptional service quality, and measurable impact on client success.",
    "about.values.label": "Our Values",
    "about.values.title": "What Drives Us Forward",
    "about.values.description": "Our core values shape every decision, every solution, and every partnership we build.",
    "about.value.innovation": "Innovation",
    "about.value.innovation.desc": "We embrace cutting-edge technologies and creative solutions to solve complex business challenges.",
    "about.value.reliability": "Reliability",
    "about.value.reliability.desc": "Our commitment to quality and consistency ensures dependable solutions you can trust.",
    "about.value.dataDriven": "Data-Driven",
    "about.value.dataDriven.desc": "Every decision is backed by data, ensuring measurable outcomes and continuous improvement.",
    "about.value.transparency": "Transparency",
    "about.value.transparency.desc": "Open communication and honest partnerships are at the core of how we work.",
    "about.team.label": "Our Team",
    "about.team.title": "Expert Professionals Dedicated to Your Success",
    "about.team.leadership": "Leadership",
    "about.team.leadership.desc": "Industry veterans with 10+ years experience",
    "about.team.engineers": "Engineers",
    "about.team.engineers.desc": "Certified developers and AI specialists",
    "about.team.consultants": "Consultants",
    "about.team.consultants.desc": "Business analysts and domain experts",
    "about.team.support": "Support",
    "about.team.support.desc": "Dedicated customer success team",
    "about.whyPartner.title": "Why Partner With Amy Tech?",
    "about.whyPartner.description": "We bring together deep technical expertise, industry knowledge, and a genuine passion for helping businesses succeed in the digital age.",
    "about.whyPartner.expertise": "Certified Expertise",
    "about.whyPartner.expertise.desc": "Our team holds industry-leading certifications in ERPNext, AI/ML, and cloud technologies.",
    "about.whyPartner.global": "Global Perspective",
    "about.whyPartner.global.desc": "We bring international best practices localized for your market and industry needs.",
    "about.whyPartner.longterm": "Long-term Partnership",
    "about.whyPartner.longterm.desc": "We're invested in your success beyond implementation, with ongoing support and optimization.",
    "about.cta.title": "Ready to Get Started?",
    "about.cta.description": "Let's discuss how we can help transform your business with AI-powered solutions tailored to your needs.",
    "about.cta.button": "Contact Us Today",

    // Services Page
    "servicesPage.badge": "Our Services",
    "servicesPage.hero.title1": "Comprehensive Solutions for",
    "servicesPage.hero.title2": "Digital Excellence",
    "servicesPage.hero.description": "From ERP implementation to AI-powered automation, we provide end-to-end solutions tailored to transform your business.",
    "servicesPage.erp.subtitle": "Comprehensive ERPNext Solutions",
    "servicesPage.erp.title": "ERP Implementation",
    "servicesPage.erp.description": "Full-scale ERPNext implementation covering all aspects of your business operations. We customize and configure the system to match your unique workflows and requirements.",
    "servicesPage.erp.finance": "Finance & Accounting",
    "servicesPage.erp.hr": "Human Resources (HR)",
    "servicesPage.erp.inventory": "Inventory Management",
    "servicesPage.erp.sales": "Sales & Distribution",
    "servicesPage.erp.procurement": "Procurement & Purchasing",
    "servicesPage.erp.workflows": "Custom Workflows & Automation",
    "servicesPage.crm.subtitle": "AI-Powered Customer Management",
    "servicesPage.crm.title": "CRM Solutions",
    "servicesPage.crm.description": "Transform your customer relationships with intelligent CRM solutions. Leverage AI to gain deeper customer insights and automate your sales pipeline.",
    "servicesPage.crm.insights": "AI-powered customer insights",
    "servicesPage.crm.pipeline": "Sales pipeline automation",
    "servicesPage.crm.leads": "Lead scoring & management",
    "servicesPage.crm.marketing": "Marketing automation",
    "servicesPage.crm.integrations": "Custom integrations",
    "servicesPage.crm.analytics": "Performance analytics",
    "servicesPage.ai.subtitle": "Intelligent Business Automation",
    "servicesPage.ai.title": "AI Solutions & Automation",
    "servicesPage.ai.description": "Harness the power of artificial intelligence to automate repetitive tasks, generate intelligent reports, and make data-driven decisions with predictive analytics.",
    "servicesPage.ai.reporting": "Intelligent reporting & dashboards",
    "servicesPage.ai.predictive": "Predictive analytics",
    "servicesPage.ai.process": "Process automation using AI",
    "servicesPage.ai.ml": "Machine learning models",
    "servicesPage.ai.alerts": "Smart alerts & forecasting",
    "servicesPage.ai.decision": "AI-driven decision support",
    "servicesPage.digital.subtitle": "Modernize Your Business",
    "servicesPage.digital.title": "Digital Transformation",
    "servicesPage.digital.description": "End-to-end digital transformation services to modernize your operations. We help you re-engineer processes and adopt cloud-based systems for maximum efficiency.",
    "servicesPage.digital.reengineering": "Business process re-engineering",
    "servicesPage.digital.cloud": "Cloud-based systems migration",
    "servicesPage.digital.legacy": "Legacy system modernization",
    "servicesPage.digital.strategy": "Digital strategy consulting",
    "servicesPage.digital.change": "Change management support",
    "servicesPage.digital.training": "Training & adoption programs",
    "servicesPage.governance.subtitle": "Audit-Ready Systems",
    "servicesPage.governance.title": "Corporate Governance & Compliance",
    "servicesPage.governance.description": "Ensure your business meets all regulatory requirements with our governance and compliance solutions. We implement policy automation and audit-ready ERP systems.",
    "servicesPage.governance.policy": "Policy automation",
    "servicesPage.governance.audit": "Audit-ready ERP systems",
    "servicesPage.governance.compliance": "Compliance monitoring",
    "servicesPage.governance.risk": "Risk management frameworks",
    "servicesPage.governance.regulatory": "Regulatory reporting",
    "servicesPage.governance.consulting": "Governance consulting",
    "servicesPage.getStarted": "Get Started",
    "servicesPage.cta.title": "Not Sure Which Service You Need?",
    "servicesPage.cta.description": "Our experts will analyze your business requirements and recommend the perfect solution tailored to your needs.",
    "servicesPage.cta.button": "Book a Free Consultation",

    // AI Capabilities Page
    "aiPage.badge": "AI Capabilities",
    "aiPage.hero.title1": "Harness the Power of",
    "aiPage.hero.title2": "Artificial Intelligence",
    "aiPage.hero.description": "We integrate cutting-edge AI across all our solutions to deliver smarter insights, automated workflows, and predictive capabilities.",
    "aiPage.core.label": "Core AI Features",
    "aiPage.core.title": "How We Use AI in Your Business",
    "aiPage.core.description": "Our AI integration spans across reporting, decision-making, automation, and predictive analytics.",
    "aiPage.reporting.title": "Reporting & Analytics",
    "aiPage.reporting.description": "Transform raw data into actionable insights with AI-powered dashboards. Our intelligent reporting systems automatically identify trends, anomalies, and opportunities.",
    "aiPage.reporting.f1": "Real-time data visualization",
    "aiPage.reporting.f2": "Automated report generation",
    "aiPage.reporting.f3": "Custom KPI tracking",
    "aiPage.reporting.f4": "Trend analysis & pattern recognition",
    "aiPage.decision.title": "Decision Support",
    "aiPage.decision.description": "Make smarter decisions faster with AI-driven recommendations. Our systems analyze complex data sets to provide clear, actionable guidance for your business.",
    "aiPage.decision.f1": "Predictive modeling",
    "aiPage.decision.f2": "Scenario analysis",
    "aiPage.decision.f3": "Risk assessment",
    "aiPage.decision.f4": "What-if simulations",
    "aiPage.workflow.title": "Workflow Automation",
    "aiPage.workflow.description": "Eliminate repetitive tasks and streamline operations with intelligent automation. Our AI learns your processes and optimizes them for maximum efficiency.",
    "aiPage.workflow.f1": "Smart task routing",
    "aiPage.workflow.f2": "Approval workflows",
    "aiPage.workflow.f3": "Document processing",
    "aiPage.workflow.f4": "Integration automation",
    "aiPage.alerts.title": "Smart Alerts & Forecasting",
    "aiPage.alerts.description": "Stay ahead of issues with proactive AI monitoring. Get intelligent alerts before problems occur and accurate forecasts to plan your next moves.",
    "aiPage.alerts.f1": "Anomaly detection",
    "aiPage.alerts.f2": "Demand forecasting",
    "aiPage.alerts.f3": "Inventory predictions",
    "aiPage.alerts.f4": "Revenue projections",
    "aiPage.useCases.label": "Use Cases",
    "aiPage.useCases.title": "AI in Action",
    "aiPage.useCases.description": "See how our AI capabilities transform real business scenarios.",
    "aiPage.useCase.sales": "Sales Optimization",
    "aiPage.useCase.sales.desc": "AI analyzes customer behavior to predict purchase likelihood and recommend next best actions.",
    "aiPage.useCase.inventory": "Inventory Management",
    "aiPage.useCase.inventory.desc": "Predictive analytics ensure optimal stock levels, reducing costs and preventing stockouts.",
    "aiPage.useCase.customer": "Customer Service",
    "aiPage.useCase.customer.desc": "AI-powered chatbots and smart routing improve response times and customer satisfaction.",
    "aiPage.useCase.financial": "Financial Planning",
    "aiPage.useCase.financial.desc": "Automated forecasting and scenario modeling for better budgeting and planning.",

    // Computer Vision Section
    "aiPage.vision.label": "Computer Vision",
    "aiPage.vision.title": "AI-Powered Computer Vision Solutions",
    "aiPage.vision.description": "Transform your operations with intelligent visual monitoring, safety compliance, and automated detection systems.",
    "aiPage.vision.core.title": "Core Computer Vision Capabilities",
    "aiPage.vision.core.description": "Our AI vision systems provide real-time monitoring, object detection, behavior analysis, and safety compliance across all environments.",
    "aiPage.vision.feature.detection": "Object & Person Detection",
    "aiPage.vision.feature.detection.desc": "Real-time identification of people, vehicles, equipment, and objects with high accuracy.",
    "aiPage.vision.feature.behavior": "Behavior Analysis",
    "aiPage.vision.feature.behavior.desc": "Intelligent monitoring of movements, crowd patterns, and anomaly detection.",
    "aiPage.vision.feature.safety": "Safety Compliance",
    "aiPage.vision.feature.safety.desc": "Automated PPE detection and safety protocol monitoring.",
    "aiPage.vision.feature.analytics": "Visual Analytics",
    "aiPage.vision.feature.analytics.desc": "Heatmaps, traffic flow analysis, and occupancy tracking.",

    // Computer Vision Industries
    "aiPage.vision.industries.title": "Industry Applications",
    "aiPage.vision.industries.description": "See how our computer vision solutions transform operations across various sectors.",
    
    "aiPage.vision.hospital": "Hospitals & Healthcare",
    "aiPage.vision.hospital.desc": "Patient monitoring, fall detection, PPE compliance for medical staff, restricted area access control, and equipment tracking.",
    "aiPage.vision.hospital.f1": "Patient fall detection & alerts",
    "aiPage.vision.hospital.f2": "Medical staff PPE compliance",
    "aiPage.vision.hospital.f3": "Visitor management & tracking",
    "aiPage.vision.hospital.f4": "Equipment location monitoring",

    "aiPage.vision.school": "Schools & Education",
    "aiPage.vision.school.desc": "Student safety monitoring, attendance tracking, unauthorized access detection, and campus security enhancement.",
    "aiPage.vision.school.f1": "Automated attendance tracking",
    "aiPage.vision.school.f2": "Campus perimeter security",
    "aiPage.vision.school.f3": "Crowd density monitoring",
    "aiPage.vision.school.f4": "Visitor identification & alerts",

    "aiPage.vision.club": "Sports Clubs & Gyms",
    "aiPage.vision.club.desc": "Member check-in, equipment usage tracking, crowd management, and facility security monitoring.",
    "aiPage.vision.club.f1": "Facial recognition check-in",
    "aiPage.vision.club.f2": "Equipment usage analytics",
    "aiPage.vision.club.f3": "Occupancy management",
    "aiPage.vision.club.f4": "Locker room security",

    "aiPage.vision.factory": "Factories & Manufacturing",
    "aiPage.vision.factory.desc": "Worker safety monitoring, PPE compliance, quality inspection, production line monitoring, and hazard detection.",
    "aiPage.vision.factory.f1": "PPE detection (helmets, vests, gloves)",
    "aiPage.vision.factory.f2": "Restricted zone monitoring",
    "aiPage.vision.factory.f3": "Quality control inspection",
    "aiPage.vision.factory.f4": "Machine operation safety",

    "aiPage.vision.construction": "Construction Sites",
    "aiPage.vision.construction.desc": "Comprehensive safety compliance monitoring, worker tracking, equipment management, and site security.",
    "aiPage.vision.construction.f1": "Hard hat & safety vest detection",
    "aiPage.vision.construction.f2": "Danger zone intrusion alerts",
    "aiPage.vision.construction.f3": "Heavy equipment proximity warnings",
    "aiPage.vision.construction.f4": "Site perimeter security",

    "aiPage.vision.retail": "Retail Stores",
    "aiPage.vision.retail.desc": "Customer behavior analytics, theft prevention, queue management, and store optimization.",
    "aiPage.vision.retail.f1": "Customer traffic analysis",
    "aiPage.vision.retail.f2": "Shoplifting detection",
    "aiPage.vision.retail.f3": "Queue length monitoring",
    "aiPage.vision.retail.f4": "Heat mapping & shelf analytics",

    "aiPage.vision.kitchen": "Central Kitchens & Food Processing",
    "aiPage.vision.kitchen.desc": "Food safety compliance, hygiene monitoring, PPE enforcement, and quality control for food preparation areas.",
    "aiPage.vision.kitchen.f1": "Hair net & glove detection",
    "aiPage.vision.kitchen.f2": "Hygiene compliance monitoring",
    "aiPage.vision.kitchen.f3": "Temperature zone monitoring",
    "aiPage.vision.kitchen.f4": "Cross-contamination prevention",

    "aiPage.vision.ppe": "PPE Compliance (All Industries)",
    "aiPage.vision.ppe.desc": "Universal personal protective equipment monitoring system applicable to any workplace requiring safety gear.",
    "aiPage.vision.ppe.f1": "Hard hats, helmets & head protection",
    "aiPage.vision.ppe.f2": "Safety vests & protective clothing",
    "aiPage.vision.ppe.f3": "Gloves, goggles & face shields",
    "aiPage.vision.ppe.f4": "Safety boots & harness detection",

    "aiPage.cta.title": "Ready to Unlock AI for Your Business?",
    "aiPage.cta.description": "Let our experts show you how AI can transform your operations, improve decision-making, and drive growth.",
    "aiPage.cta.button": "Schedule AI Consultation",

    // ERPNext Page
    "erpPage.badge": "ERPNext Solutions",
    "erpPage.hero.title1": "Transform Your Business with",
    "erpPage.hero.title2": "ERPNext",
    "erpPage.hero.description": "The world's most versatile open-source ERP system, implemented and customized by Amy Tech for your unique business needs.",
    "erpPage.hero.cta1": "Get ERPNext Quote",
    "erpPage.hero.cta2": "View ERP Services",
    "erpPage.why.label": "Why ERPNext",
    "erpPage.why.title": "The Smart Choice for Modern Businesses",
    "erpPage.why.description": "ERPNext offers enterprise-grade features at a fraction of the cost of proprietary systems.",
    "erpPage.why.openSource": "Open Source & Flexible",
    "erpPage.why.openSource.desc": "ERPNext is built on open-source technology, giving you full control and customization capabilities without vendor lock-in.",
    "erpPage.why.allInOne": "All-in-One Solution",
    "erpPage.why.allInOne.desc": "A complete business management system covering Accounting, HR, Manufacturing, Sales, CRM, and more in one integrated platform.",
    "erpPage.why.costEffective": "Cost-Effective",
    "erpPage.why.costEffective.desc": "No per-user licensing fees. Pay for implementation and support, not software licenses that scale with your growth.",
    "erpPage.why.customizable": "Highly Customizable",
    "erpPage.why.customizable.desc": "Every business is unique. ERPNext can be tailored to match your exact workflows and requirements.",
    "erpPage.partner.label": "Why Amy Tech",
    "erpPage.partner.title": "Your Trusted ERPNext Implementation Partner",
    "erpPage.partner.description": "With deep expertise in ERPNext and a commitment to your success, we deliver implementations that truly transform your business.",
    "erpPage.partner.certified": "Certified Expertise",
    "erpPage.partner.certified.desc": "Our team has extensive experience implementing ERPNext across diverse industries and business sizes.",
    "erpPage.partner.aiEnhanced": "AI-Enhanced",
    "erpPage.partner.aiEnhanced.desc": "We augment ERPNext with AI capabilities for smarter automation, analytics, and decision support.",
    "erpPage.partner.endToEnd": "End-to-End Support",
    "erpPage.partner.endToEnd.desc": "From initial consulting to implementation, training, and ongoing support – we're with you every step.",
    "erpPage.partner.industry": "Industry Knowledge",
    "erpPage.partner.industry.desc": "We understand the specific requirements of manufacturing, retail, logistics, and services sectors.",
    "erpPage.process.title": "Our Implementation Process",
    "erpPage.process.step1": "Discovery",
    "erpPage.process.step1.desc": "Understand your business needs",
    "erpPage.process.step2": "Design",
    "erpPage.process.step2.desc": "Plan the solution architecture",
    "erpPage.process.step3": "Implementation",
    "erpPage.process.step3.desc": "Configure and customize ERPNext",
    "erpPage.process.step4": "Training",
    "erpPage.process.step4.desc": "Empower your team",
    "erpPage.process.step5": "Go-Live & Support",
    "erpPage.process.step5.desc": "Launch and continuous improvement",
    "erpPage.industries.label": "Industries",
    "erpPage.industries.title": "ERPNext Solutions for Every Industry",
    "erpPage.industries.description": "We have experience implementing ERPNext across diverse sectors with industry-specific customizations.",
    "erpPage.industry.manufacturing": "Manufacturing",
    "erpPage.industry.manufacturing.desc": "Production planning, BOM management, quality control, and shop floor operations.",
    "erpPage.industry.manufacturing.f1": "Work Order Management",
    "erpPage.industry.manufacturing.f2": "Bill of Materials",
    "erpPage.industry.manufacturing.f3": "Quality Inspection",
    "erpPage.industry.manufacturing.f4": "Subcontracting",
    "erpPage.industry.retail": "Retail & E-commerce",
    "erpPage.industry.retail.desc": "POS integration, inventory management, multi-channel sales, and customer loyalty programs.",
    "erpPage.industry.retail.f1": "Point of Sale",
    "erpPage.industry.retail.f2": "E-commerce Integration",
    "erpPage.industry.retail.f3": "Loyalty Programs",
    "erpPage.industry.retail.f4": "Multi-location Inventory",
    "erpPage.industry.logistics": "Logistics & Distribution",
    "erpPage.industry.logistics.desc": "Warehouse management, fleet tracking, delivery optimization, and supply chain visibility.",
    "erpPage.industry.logistics.f1": "Warehouse Management",
    "erpPage.industry.logistics.f2": "Fleet Management",
    "erpPage.industry.logistics.f3": "Route Optimization",
    "erpPage.industry.logistics.f4": "Real-time Tracking",
    "erpPage.industry.services": "Professional Services",
    "erpPage.industry.services.desc": "Project management, timesheet tracking, resource allocation, and client billing.",
    "erpPage.industry.services.f1": "Project Tracking",
    "erpPage.industry.services.f2": "Timesheet Management",
    "erpPage.industry.services.f3": "Resource Planning",
    "erpPage.industry.services.f4": "Client Portals",
    "erpPage.industry.healthcare": "Healthcare",
    "erpPage.industry.healthcare.desc": "Patient management, appointment scheduling, inventory for medical supplies, and compliance.",
    "erpPage.industry.healthcare.f1": "Patient Records",
    "erpPage.industry.healthcare.f2": "Appointment Scheduling",
    "erpPage.industry.healthcare.f3": "Medical Inventory",
    "erpPage.industry.healthcare.f4": "Compliance Tracking",
    "erpPage.industry.education": "Education",
    "erpPage.industry.education.desc": "Student information systems, fee management, course planning, and academic tracking.",
    "erpPage.industry.education.f1": "Student Information",
    "erpPage.industry.education.f2": "Fee Management",
    "erpPage.industry.education.f3": "Course Planning",
    "erpPage.industry.education.f4": "Academic Reports",
    "erpPage.cta.title": "Ready to Implement ERPNext?",
    "erpPage.cta.description": "Let's discuss how ERPNext can streamline your operations and drive business growth.",
    "erpPage.cta.button": "Start Your ERPNext Journey",

    // Contact Page
    "contactPage.badge": "Contact Us",
    "contactPage.hero.title1": "Let's Start Your",
    "contactPage.hero.title2": "Digital Journey",
    "contactPage.hero.description": "Get in touch with our experts for a free consultation and discover how we can transform your business.",
    "contactPage.form.title": "Send Us a Message",
    "contactPage.form.name": "Full Name",
    "contactPage.form.namePlaceholder": "John Doe",
    "contactPage.form.email": "Email Address",
    "contactPage.form.emailPlaceholder": "john@company.com",
    "contactPage.form.phone": "Phone Number",
    "contactPage.form.phonePlaceholder": "+966 5XX XXX XXXX",
    "contactPage.form.company": "Company Name",
    "contactPage.form.companyPlaceholder": "Your Company",
    "contactPage.form.service": "Service Interested In",
    "contactPage.form.servicePlaceholder": "Select a service",
    "contactPage.form.message": "Your Message",
    "contactPage.form.messagePlaceholder": "Tell us about your project requirements...",
    "contactPage.form.submit": "Send Message",
    "contactPage.form.submitting": "Sending...",
    "contactPage.form.required": "*",
    "contactPage.info.title": "Get in Touch",
    "contactPage.info.description": "Have questions? We're here to help. Reach out through any of the channels below.",
    "contactPage.info.phone": "Phone",
    "contactPage.info.email": "Email",
    "contactPage.info.hours": "Business Hours",
    "contactPage.info.hoursValue": "Sun - Thu: 9AM - 6PM",
    "contactPage.expect.title": "What to Expect",
    "contactPage.expect.item1": "Response within 24 hours",
    "contactPage.expect.item2": "Free initial consultation",
    "contactPage.expect.item3": "Customized solution proposal",
    "contactPage.expect.item4": "Transparent pricing",
    "contactPage.services.erp": "ERP Implementation",
    "contactPage.services.crm": "CRM Solutions",
    "contactPage.services.ai": "AI Automation",
    "contactPage.services.digital": "Digital Transformation",
    "contactPage.services.governance": "Corporate Governance",
    "contactPage.services.other": "Other",
    "contactPage.toast.title": "Message Sent Successfully!",
"contactPage.toast.description": "Thank you for contacting us. Our team will get back to you within 24 hours.",
    "whatsapp.title": "Get in Touch Fast via WhatsApp",
    "whatsapp.subtitle": "Our team responds within minutes. Fastest way to start your project.",
    "whatsapp.button": "Start WhatsApp Chat",
    "whatsapp.phone": "+966 58 314 0470",
  },

  ar: {
    // Header
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.services": "خدماتنا",
    "nav.ai": "قدرات الذكاء الاصطناعي",
    "nav.erpnext": "ERPNext",
    "nav.contact": "اتصل بنا",
    "nav.getStarted": "ابدأ الآن",

    // Hero
    "hero.badge": "حلول مدعومة بالذكاء الاصطناعي",
    "hero.title1": "التحول الرقمي الذكي",
    "hero.title2": "مدعوم بالذكاء الاصطناعي",
    "hero.title3": "و ERPNext",
    "hero.description": "قم بتمكين عملك من خلال أتمتة الذكاء الاصطناعي المتطورة وحلول تخطيط موارد المؤسسات الشاملة واتخاذ القرارات المستندة إلى البيانات. غيّر طريقة عملك.",
    "hero.cta1": "احجز استشارة مجانية",
    "hero.cta2": "اطلب عرضًا توضيحيًا",
    "hero.trusted": "موثوق من قبل الشركات الرائدة في مختلف الصناعات",

    // Industries
    "industry.manufacturing": "التصنيع",
    "industry.retail": "التجزئة",
    "industry.logistics": "الخدمات اللوجستية",
    "industry.services": "الخدمات",

    // Services Section
    "services.label": "خدماتنا",
    "services.title1": "حلول شاملة",
    "services.title2": "للأعمال الحديثة",
    "services.description": "من تنفيذ تخطيط موارد المؤسسات إلى الأتمتة المدعومة بالذكاء الاصطناعي، نقدم حلولاً شاملة مصممة خصيصًا لاحتياجات عملك.",
    "services.learnMore": "اعرف المزيد",

    // Service Items
    "service.erp.title": "تنفيذ نظام ERP",
    "service.erp.description": "تنفيذ ERPNext الكامل الذي يغطي المالية والموارد البشرية والمخزون والمبيعات والمشتريات مع سير عمل مخصص.",
    "service.crm.title": "حلول إدارة العملاء",
    "service.crm.description": "رؤى العملاء المدعومة بالذكاء الاصطناعي وأتمتة خط المبيعات لتحسين علاقات العملاء.",
    "service.ai.title": "أتمتة الذكاء الاصطناعي",
    "service.ai.description": "التقارير الذكية والتحليلات التنبؤية وأتمتة العمليات باستخدام أحدث تقنيات الذكاء الاصطناعي.",
    "service.digital.title": "التحول الرقمي",
    "service.digital.description": "إعادة هندسة العمليات التجارية وتحديث الأنظمة السحابية.",
    "service.governance.title": "الحوكمة المؤسسية",
    "service.governance.description": "أتمتة السياسات وأنظمة ERP الجاهزة للتدقيق للتميز في الامتثال.",
    "service.analytics.title": "تحليلات البيانات",
    "service.analytics.description": "تحويل البيانات الخام إلى رؤى قابلة للتنفيذ باستخدام لوحات معلومات وتقارير مدعومة بالذكاء الاصطناعي.",

    // Why Amy Tech
    "why.label": "لماذا Amy Tech",
    "why.title1": "شريكك الموثوق",
    "why.title2": "للتميز الرقمي",
    "why.description": "نجمع بين الخبرة الصناعية العميقة وتقنيات الذكاء الاصطناعي المتطورة لتقديم حلول تحقق نتائج أعمال حقيقية.",
    "why.item1": "شركاء معتمدون لتنفيذ ERPNext",
    "why.item2": "نهج الذكاء الاصطناعي أولاً في جميع الحلول",
    "why.item3": "فريق دعم مخصص على مدار الساعة",
    "why.item4": "سجل حافل عبر الصناعات",
    "why.item5": "حلول مخصصة لاحتياجاتك",
    "why.learnMore": "اعرف المزيد عنا",

    // Feature Cards
    "feature.aiPowered": "مدعوم بالذكاء الاصطناعي",
    "feature.aiPowered.desc": "الأتمتة الذكية والتحليلات التنبؤية",
    "feature.erpnext": "ERPNext",
    "feature.erpnext.desc": "نظام إدارة أعمال متكامل",
    "feature.secure": "آمن",
    "feature.secure.desc": "أمان على مستوى المؤسسات والامتثال",
    "feature.scalable": "قابل للتوسع",
    "feature.scalable.desc": "نمو بدون قيود",

    // CTA Section
    "cta.title": "هل أنت مستعد لتحويل عملك؟",
    "cta.description": "حدد موعدًا لاستشارة مجانية مع خبرائنا واكتشف كيف يمكن للحلول المدعومة بالذكاء الاصطناعي أن تحدث ثورة في عملياتك.",
    "cta.button1": "احجز استشارة مجانية",
    "cta.button2": "استكشف الخدمات",

    // Footer
    "footer.description": "تمكين الأعمال من خلال حلول ERP و CRM المدعومة بالذكاء الاصطناعي. شريكك الموثوق للتحول الرقمي والحوكمة المؤسسية.",
    "footer.company": "الشركة",
    "footer.services": "الخدمات",
    "footer.contact": "اتصل بنا",
    "footer.rights": "جميع الحقوق محفوظة.",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",

    // Language
    "lang.switch": "English",

    // About Page
    "about.badge": "من نحن",
    "about.hero.title1": "تمكين الأعمال من خلال",
    "about.hero.title2": "ابتكار الذكاء الاصطناعي",
    "about.hero.description": "نحن شركة تقنية ناشئة مكرسة لتحويل الأعمال من خلال حلول ERP و CRM المدعومة بالذكاء الاصطناعي والتميز الرقمي.",
    "about.mission.title": "مهمتنا",
    "about.mission.description": "تمكين الأعمال من خلال حلول ERP و CRM المدعومة بالذكاء الاصطناعي، مما يمكنها من تحقيق التميز التشغيلي واتخاذ قرارات مستندة إلى البيانات والبقاء في المقدمة في مشهد رقمي متطور باستمرار.",
    "about.vision.title": "رؤيتنا",
    "about.vision.description": "أن نصبح شريكًا رائدًا في التحول الرقمي والحوكمة المؤسسية، معترفًا به عالميًا لحلول الذكاء الاصطناعي المبتكرة وجودة الخدمة الاستثنائية والتأثير القابل للقياس على نجاح العملاء.",
    "about.values.label": "قيمنا",
    "about.values.title": "ما يدفعنا إلى الأمام",
    "about.values.description": "قيمنا الأساسية تشكل كل قرار وكل حل وكل شراكة نبنيها.",
    "about.value.innovation": "الابتكار",
    "about.value.innovation.desc": "نحتضن أحدث التقنيات والحلول الإبداعية لحل تحديات الأعمال المعقدة.",
    "about.value.reliability": "الموثوقية",
    "about.value.reliability.desc": "التزامنا بالجودة والاتساق يضمن حلولاً يمكن الاعتماد عليها.",
    "about.value.dataDriven": "القرارات المستندة إلى البيانات",
    "about.value.dataDriven.desc": "كل قرار مدعوم بالبيانات، مما يضمن نتائج قابلة للقياس وتحسين مستمر.",
    "about.value.transparency": "الشفافية",
    "about.value.transparency.desc": "التواصل المفتوح والشراكات الصادقة هي جوهر طريقة عملنا.",
    "about.team.label": "فريقنا",
    "about.team.title": "محترفون خبراء مكرسون لنجاحك",
    "about.team.leadership": "القيادة",
    "about.team.leadership.desc": "خبراء في الصناعة بخبرة تزيد عن 10 سنوات",
    "about.team.engineers": "المهندسون",
    "about.team.engineers.desc": "مطورون معتمدون ومتخصصون في الذكاء الاصطناعي",
    "about.team.consultants": "المستشارون",
    "about.team.consultants.desc": "محللو أعمال وخبراء في المجال",
    "about.team.support": "الدعم",
    "about.team.support.desc": "فريق مخصص لنجاح العملاء",
    "about.whyPartner.title": "لماذا تشارك مع Amy Tech؟",
    "about.whyPartner.description": "نجمع بين الخبرة التقنية العميقة ومعرفة الصناعة والشغف الحقيقي لمساعدة الأعمال على النجاح في العصر الرقمي.",
    "about.whyPartner.expertise": "خبرة معتمدة",
    "about.whyPartner.expertise.desc": "يحمل فريقنا شهادات رائدة في الصناعة في ERPNext و AI/ML وتقنيات السحابة.",
    "about.whyPartner.global": "منظور عالمي",
    "about.whyPartner.global.desc": "نجلب أفضل الممارسات الدولية المحلية لسوقك واحتياجات صناعتك.",
    "about.whyPartner.longterm": "شراكة طويلة الأمد",
    "about.whyPartner.longterm.desc": "نحن ملتزمون بنجاحك بعد التنفيذ، مع الدعم المستمر والتحسين.",
    "about.cta.title": "هل أنت مستعد للبدء؟",
    "about.cta.description": "دعنا نناقش كيف يمكننا المساعدة في تحويل عملك بحلول مدعومة بالذكاء الاصطناعي مصممة لاحتياجاتك.",
    "about.cta.button": "تواصل معنا اليوم",

    // Services Page
    "servicesPage.badge": "خدماتنا",
    "servicesPage.hero.title1": "حلول شاملة لتحقيق",
    "servicesPage.hero.title2": "التميز الرقمي",
    "servicesPage.hero.description": "من تنفيذ ERP إلى الأتمتة المدعومة بالذكاء الاصطناعي، نقدم حلولاً شاملة مصممة لتحويل عملك.",
    "servicesPage.erp.subtitle": "حلول ERPNext الشاملة",
    "servicesPage.erp.title": "تنفيذ نظام ERP",
    "servicesPage.erp.description": "تنفيذ ERPNext على نطاق واسع يغطي جميع جوانب عمليات عملك. نقوم بتخصيص وتكوين النظام ليتوافق مع سير عملك ومتطلباتك الفريدة.",
    "servicesPage.erp.finance": "المالية والمحاسبة",
    "servicesPage.erp.hr": "الموارد البشرية",
    "servicesPage.erp.inventory": "إدارة المخزون",
    "servicesPage.erp.sales": "المبيعات والتوزيع",
    "servicesPage.erp.procurement": "المشتريات والتوريد",
    "servicesPage.erp.workflows": "سير العمل المخصص والأتمتة",
    "servicesPage.crm.subtitle": "إدارة العملاء المدعومة بالذكاء الاصطناعي",
    "servicesPage.crm.title": "حلول إدارة علاقات العملاء",
    "servicesPage.crm.description": "حوّل علاقاتك مع العملاء من خلال حلول CRM الذكية. استفد من الذكاء الاصطناعي للحصول على رؤى أعمق عن العملاء وأتمتة خط المبيعات.",
    "servicesPage.crm.insights": "رؤى العملاء المدعومة بالذكاء الاصطناعي",
    "servicesPage.crm.pipeline": "أتمتة خط المبيعات",
    "servicesPage.crm.leads": "تسجيل وإدارة العملاء المحتملين",
    "servicesPage.crm.marketing": "أتمتة التسويق",
    "servicesPage.crm.integrations": "التكاملات المخصصة",
    "servicesPage.crm.analytics": "تحليلات الأداء",
    "servicesPage.ai.subtitle": "أتمتة الأعمال الذكية",
    "servicesPage.ai.title": "حلول الذكاء الاصطناعي والأتمتة",
    "servicesPage.ai.description": "استفد من قوة الذكاء الاصطناعي لأتمتة المهام المتكررة وإنشاء تقارير ذكية واتخاذ قرارات مستندة إلى البيانات مع التحليلات التنبؤية.",
    "servicesPage.ai.reporting": "التقارير ولوحات المعلومات الذكية",
    "servicesPage.ai.predictive": "التحليلات التنبؤية",
    "servicesPage.ai.process": "أتمتة العمليات باستخدام الذكاء الاصطناعي",
    "servicesPage.ai.ml": "نماذج تعلم الآلة",
    "servicesPage.ai.alerts": "التنبيهات الذكية والتنبؤ",
    "servicesPage.ai.decision": "دعم القرار المدعوم بالذكاء الاصطناعي",
    "servicesPage.digital.subtitle": "حدّث عملك",
    "servicesPage.digital.title": "التحول الرقمي",
    "servicesPage.digital.description": "خدمات التحول الرقمي الشاملة لتحديث عملياتك. نساعدك على إعادة هندسة العمليات واعتماد الأنظمة السحابية لتحقيق أقصى كفاءة.",
    "servicesPage.digital.reengineering": "إعادة هندسة العمليات التجارية",
    "servicesPage.digital.cloud": "الانتقال إلى الأنظمة السحابية",
    "servicesPage.digital.legacy": "تحديث الأنظمة القديمة",
    "servicesPage.digital.strategy": "استشارات الاستراتيجية الرقمية",
    "servicesPage.digital.change": "دعم إدارة التغيير",
    "servicesPage.digital.training": "برامج التدريب والاعتماد",
    "servicesPage.governance.subtitle": "أنظمة جاهزة للتدقيق",
    "servicesPage.governance.title": "الحوكمة المؤسسية والامتثال",
    "servicesPage.governance.description": "تأكد من أن عملك يلبي جميع المتطلبات التنظيمية من خلال حلول الحوكمة والامتثال. ننفذ أتمتة السياسات وأنظمة ERP الجاهزة للتدقيق.",
    "servicesPage.governance.policy": "أتمتة السياسات",
    "servicesPage.governance.audit": "أنظمة ERP الجاهزة للتدقيق",
    "servicesPage.governance.compliance": "مراقبة الامتثال",
    "servicesPage.governance.risk": "أطر إدارة المخاطر",
    "servicesPage.governance.regulatory": "التقارير التنظيمية",
    "servicesPage.governance.consulting": "استشارات الحوكمة",
    "servicesPage.getStarted": "ابدأ الآن",
    "servicesPage.cta.title": "لست متأكدًا من الخدمة التي تحتاجها؟",
    "servicesPage.cta.description": "سيقوم خبراؤنا بتحليل متطلبات عملك والتوصية بالحل المثالي المصمم لاحتياجاتك.",
    "servicesPage.cta.button": "احجز استشارة مجانية",

    // AI Capabilities Page
    "aiPage.badge": "قدرات الذكاء الاصطناعي",
    "aiPage.hero.title1": "استفد من قوة",
    "aiPage.hero.title2": "الذكاء الاصطناعي",
    "aiPage.hero.description": "ندمج أحدث تقنيات الذكاء الاصطناعي في جميع حلولنا لتقديم رؤى أذكى وسير عمل مؤتمت وقدرات تنبؤية.",
    "aiPage.core.label": "ميزات الذكاء الاصطناعي الأساسية",
    "aiPage.core.title": "كيف نستخدم الذكاء الاصطناعي في عملك",
    "aiPage.core.description": "يمتد تكامل الذكاء الاصطناعي لدينا عبر التقارير واتخاذ القرارات والأتمتة والتحليلات التنبؤية.",
    "aiPage.reporting.title": "التقارير والتحليلات",
    "aiPage.reporting.description": "حوّل البيانات الخام إلى رؤى قابلة للتنفيذ باستخدام لوحات معلومات مدعومة بالذكاء الاصطناعي. تحدد أنظمة التقارير الذكية لدينا تلقائيًا الاتجاهات والشذوذ والفرص.",
    "aiPage.reporting.f1": "تصور البيانات في الوقت الفعلي",
    "aiPage.reporting.f2": "إنشاء التقارير الآلي",
    "aiPage.reporting.f3": "تتبع مؤشرات الأداء الرئيسية المخصصة",
    "aiPage.reporting.f4": "تحليل الاتجاهات والتعرف على الأنماط",
    "aiPage.decision.title": "دعم القرار",
    "aiPage.decision.description": "اتخذ قرارات أذكى بشكل أسرع مع التوصيات المدعومة بالذكاء الاصطناعي. تحلل أنظمتنا مجموعات البيانات المعقدة لتوفير إرشادات واضحة وقابلة للتنفيذ لعملك.",
    "aiPage.decision.f1": "النمذجة التنبؤية",
    "aiPage.decision.f2": "تحليل السيناريوهات",
    "aiPage.decision.f3": "تقييم المخاطر",
    "aiPage.decision.f4": "محاكاة ماذا لو",
    "aiPage.workflow.title": "أتمتة سير العمل",
    "aiPage.workflow.description": "تخلص من المهام المتكررة وبسّط العمليات من خلال الأتمتة الذكية. يتعلم ذكاؤنا الاصطناعي عملياتك ويحسنها لتحقيق أقصى كفاءة.",
    "aiPage.workflow.f1": "توجيه المهام الذكي",
    "aiPage.workflow.f2": "سير عمل الموافقات",
    "aiPage.workflow.f3": "معالجة المستندات",
    "aiPage.workflow.f4": "أتمتة التكامل",
    "aiPage.alerts.title": "التنبيهات الذكية والتنبؤ",
    "aiPage.alerts.description": "ابقَ متقدمًا على المشكلات من خلال مراقبة الذكاء الاصطناعي الاستباقية. احصل على تنبيهات ذكية قبل حدوث المشكلات وتنبؤات دقيقة للتخطيط لخطواتك التالية.",
    "aiPage.alerts.f1": "اكتشاف الشذوذ",
    "aiPage.alerts.f2": "التنبؤ بالطلب",
    "aiPage.alerts.f3": "توقعات المخزون",
    "aiPage.alerts.f4": "توقعات الإيرادات",
    "aiPage.useCases.label": "حالات الاستخدام",
    "aiPage.useCases.title": "الذكاء الاصطناعي في العمل",
    "aiPage.useCases.description": "شاهد كيف تحول قدرات الذكاء الاصطناعي لدينا سيناريوهات الأعمال الحقيقية.",
    "aiPage.useCase.sales": "تحسين المبيعات",
    "aiPage.useCase.sales.desc": "يحلل الذكاء الاصطناعي سلوك العملاء للتنبؤ باحتمالية الشراء والتوصية بأفضل الإجراءات التالية.",
    "aiPage.useCase.inventory": "إدارة المخزون",
    "aiPage.useCase.inventory.desc": "تضمن التحليلات التنبؤية مستويات المخزون المثلى، مما يقلل التكاليف ويمنع نفاد المخزون.",
    "aiPage.useCase.customer": "خدمة العملاء",
    "aiPage.useCase.customer.desc": "تحسن روبوتات الدردشة المدعومة بالذكاء الاصطناعي والتوجيه الذكي أوقات الاستجابة ورضا العملاء.",
    "aiPage.useCase.financial": "التخطيط المالي",
    "aiPage.useCase.financial.desc": "التنبؤ الآلي ونمذجة السيناريوهات لتحسين الميزانية والتخطيط.",

    // Computer Vision Section
    "aiPage.vision.label": "الرؤية الحاسوبية",
    "aiPage.vision.title": "حلول الرؤية الحاسوبية المدعومة بالذكاء الاصطناعي",
    "aiPage.vision.description": "حوّل عملياتك من خلال المراقبة البصرية الذكية والامتثال للسلامة وأنظمة الكشف الآلية.",
    "aiPage.vision.core.title": "قدرات الرؤية الحاسوبية الأساسية",
    "aiPage.vision.core.description": "توفر أنظمة الرؤية الذكية لدينا مراقبة في الوقت الفعلي وكشف الأجسام وتحليل السلوك والامتثال للسلامة في جميع البيئات.",
    "aiPage.vision.feature.detection": "كشف الأجسام والأشخاص",
    "aiPage.vision.feature.detection.desc": "التعرف في الوقت الفعلي على الأشخاص والمركبات والمعدات والأجسام بدقة عالية.",
    "aiPage.vision.feature.behavior": "تحليل السلوك",
    "aiPage.vision.feature.behavior.desc": "مراقبة ذكية للحركات وأنماط الحشود واكتشاف الشذوذ.",
    "aiPage.vision.feature.safety": "الامتثال للسلامة",
    "aiPage.vision.feature.safety.desc": "الكشف الآلي عن معدات الحماية الشخصية ومراقبة بروتوكولات السلامة.",
    "aiPage.vision.feature.analytics": "التحليلات البصرية",
    "aiPage.vision.feature.analytics.desc": "خرائط الحرارة وتحليل تدفق الحركة وتتبع الإشغال.",

    // Computer Vision Industries
    "aiPage.vision.industries.title": "التطبيقات الصناعية",
    "aiPage.vision.industries.description": "شاهد كيف تحول حلول الرؤية الحاسوبية لدينا العمليات عبر مختلف القطاعات.",
    
    "aiPage.vision.hospital": "المستشفيات والرعاية الصحية",
    "aiPage.vision.hospital.desc": "مراقبة المرضى، اكتشاف السقوط، الامتثال لمعدات الحماية للطاقم الطبي، التحكم في الوصول للمناطق المحظورة، وتتبع المعدات.",
    "aiPage.vision.hospital.f1": "اكتشاف سقوط المرضى والتنبيهات",
    "aiPage.vision.hospital.f2": "امتثال الطاقم الطبي لمعدات الحماية",
    "aiPage.vision.hospital.f3": "إدارة وتتبع الزوار",
    "aiPage.vision.hospital.f4": "مراقبة موقع المعدات",

    "aiPage.vision.school": "المدارس والتعليم",
    "aiPage.vision.school.desc": "مراقبة سلامة الطلاب، تتبع الحضور، اكتشاف الوصول غير المصرح به، وتعزيز أمن الحرم.",
    "aiPage.vision.school.f1": "تتبع الحضور الآلي",
    "aiPage.vision.school.f2": "أمن محيط الحرم",
    "aiPage.vision.school.f3": "مراقبة كثافة الحشود",
    "aiPage.vision.school.f4": "تحديد الزوار والتنبيهات",

    "aiPage.vision.club": "النوادي الرياضية والصالات",
    "aiPage.vision.club.desc": "تسجيل دخول الأعضاء، تتبع استخدام المعدات، إدارة الحشود، ومراقبة أمن المنشأة.",
    "aiPage.vision.club.f1": "تسجيل الدخول بالتعرف على الوجه",
    "aiPage.vision.club.f2": "تحليلات استخدام المعدات",
    "aiPage.vision.club.f3": "إدارة الإشغال",
    "aiPage.vision.club.f4": "أمن غرف تبديل الملابس",

    "aiPage.vision.factory": "المصانع والتصنيع",
    "aiPage.vision.factory.desc": "مراقبة سلامة العمال، الامتثال لمعدات الحماية، فحص الجودة، مراقبة خط الإنتاج، واكتشاف المخاطر.",
    "aiPage.vision.factory.f1": "كشف معدات الحماية (الخوذ، السترات، القفازات)",
    "aiPage.vision.factory.f2": "مراقبة المناطق المحظورة",
    "aiPage.vision.factory.f3": "فحص مراقبة الجودة",
    "aiPage.vision.factory.f4": "سلامة تشغيل الآلات",

    "aiPage.vision.construction": "مواقع البناء",
    "aiPage.vision.construction.desc": "مراقبة شاملة للامتثال للسلامة، تتبع العمال، إدارة المعدات، وأمن الموقع.",
    "aiPage.vision.construction.f1": "كشف الخوذ وسترات السلامة",
    "aiPage.vision.construction.f2": "تنبيهات اختراق مناطق الخطر",
    "aiPage.vision.construction.f3": "تحذيرات قرب المعدات الثقيلة",
    "aiPage.vision.construction.f4": "أمن محيط الموقع",

    "aiPage.vision.retail": "متاجر التجزئة",
    "aiPage.vision.retail.desc": "تحليلات سلوك العملاء، منع السرقة، إدارة الطوابير، وتحسين المتجر.",
    "aiPage.vision.retail.f1": "تحليل حركة العملاء",
    "aiPage.vision.retail.f2": "اكتشاف السرقة",
    "aiPage.vision.retail.f3": "مراقبة طول الطوابير",
    "aiPage.vision.retail.f4": "خرائط الحرارة وتحليلات الرفوف",

    "aiPage.vision.kitchen": "المطابخ المركزية ومعالجة الأغذية",
    "aiPage.vision.kitchen.desc": "الامتثال لسلامة الغذاء، مراقبة النظافة، تطبيق معدات الحماية، ومراقبة الجودة لمناطق إعداد الطعام.",
    "aiPage.vision.kitchen.f1": "كشف غطاء الشعر والقفازات",
    "aiPage.vision.kitchen.f2": "مراقبة الامتثال للنظافة",
    "aiPage.vision.kitchen.f3": "مراقبة مناطق درجة الحرارة",
    "aiPage.vision.kitchen.f4": "منع التلوث المتبادل",

    "aiPage.vision.ppe": "الامتثال لمعدات الحماية (جميع الصناعات)",
    "aiPage.vision.ppe.desc": "نظام مراقبة معدات الحماية الشخصية العالمي القابل للتطبيق في أي مكان عمل يتطلب معدات السلامة.",
    "aiPage.vision.ppe.f1": "الخوذ وحماية الرأس",
    "aiPage.vision.ppe.f2": "سترات السلامة والملابس الواقية",
    "aiPage.vision.ppe.f3": "القفازات والنظارات وواقيات الوجه",
    "aiPage.vision.ppe.f4": "أحذية السلامة واكتشاف الحزام",

    "aiPage.cta.title": "هل أنت مستعد لإطلاق الذكاء الاصطناعي لعملك؟",
    "aiPage.cta.description": "دع خبراءنا يوضحون لك كيف يمكن للذكاء الاصطناعي تحويل عملياتك وتحسين اتخاذ القرارات ودفع النمو.",
    "aiPage.cta.button": "حدد موعد استشارة الذكاء الاصطناعي",

    // ERPNext Page
    "erpPage.badge": "حلول ERPNext",
    "erpPage.hero.title1": "حوّل عملك مع",
    "erpPage.hero.title2": "ERPNext",
    "erpPage.hero.description": "نظام ERP مفتوح المصدر الأكثر تنوعًا في العالم، يتم تنفيذه وتخصيصه بواسطة Amy Tech لاحتياجات عملك الفريدة.",
    "erpPage.hero.cta1": "احصل على عرض سعر ERPNext",
    "erpPage.hero.cta2": "عرض خدمات ERP",
    "erpPage.why.label": "لماذا ERPNext",
    "erpPage.why.title": "الخيار الذكي للأعمال الحديثة",
    "erpPage.why.description": "يوفر ERPNext ميزات على مستوى المؤسسات بجزء بسيط من تكلفة الأنظمة الاحتكارية.",
    "erpPage.why.openSource": "مفتوح المصدر ومرن",
    "erpPage.why.openSource.desc": "بُني ERPNext على تقنية مفتوحة المصدر، مما يمنحك التحكم الكامل وقدرات التخصيص دون الارتباط بمورد معين.",
    "erpPage.why.allInOne": "حل متكامل",
    "erpPage.why.allInOne.desc": "نظام إدارة أعمال متكامل يغطي المحاسبة والموارد البشرية والتصنيع والمبيعات وإدارة العملاء والمزيد في منصة واحدة.",
    "erpPage.why.costEffective": "فعال من حيث التكلفة",
    "erpPage.why.costEffective.desc": "لا رسوم ترخيص لكل مستخدم. ادفع مقابل التنفيذ والدعم، وليس تراخيص البرامج التي تتوسع مع نموك.",
    "erpPage.why.customizable": "قابل للتخصيص بدرجة عالية",
    "erpPage.why.customizable.desc": "كل عمل فريد من نوعه. يمكن تصميم ERPNext ليتوافق مع سير عملك ومتطلباتك بالضبط.",
    "erpPage.partner.label": "لماذا Amy Tech",
    "erpPage.partner.title": "شريكك الموثوق لتنفيذ ERPNext",
    "erpPage.partner.description": "مع خبرة عميقة في ERPNext والتزام بنجاحك، نقدم تنفيذات تحول عملك حقًا.",
    "erpPage.partner.certified": "خبرة معتمدة",
    "erpPage.partner.certified.desc": "يتمتع فريقنا بخبرة واسعة في تنفيذ ERPNext عبر صناعات وأحجام أعمال متنوعة.",
    "erpPage.partner.aiEnhanced": "معزز بالذكاء الاصطناعي",
    "erpPage.partner.aiEnhanced.desc": "نعزز ERPNext بقدرات الذكاء الاصطناعي لأتمتة أذكى وتحليلات ودعم قرارات.",
    "erpPage.partner.endToEnd": "دعم شامل",
    "erpPage.partner.endToEnd.desc": "من الاستشارة الأولية إلى التنفيذ والتدريب والدعم المستمر - نحن معك في كل خطوة.",
    "erpPage.partner.industry": "معرفة بالصناعة",
    "erpPage.partner.industry.desc": "نفهم المتطلبات المحددة لقطاعات التصنيع والتجزئة والخدمات اللوجستية والخدمات.",
    "erpPage.process.title": "عملية التنفيذ لدينا",
    "erpPage.process.step1": "الاكتشاف",
    "erpPage.process.step1.desc": "فهم احتياجات عملك",
    "erpPage.process.step2": "التصميم",
    "erpPage.process.step2.desc": "تخطيط بنية الحل",
    "erpPage.process.step3": "التنفيذ",
    "erpPage.process.step3.desc": "تكوين وتخصيص ERPNext",
    "erpPage.process.step4": "التدريب",
    "erpPage.process.step4.desc": "تمكين فريقك",
    "erpPage.process.step5": "الإطلاق والدعم",
    "erpPage.process.step5.desc": "الإطلاق والتحسين المستمر",
    "erpPage.industries.label": "الصناعات",
    "erpPage.industries.title": "حلول ERPNext لكل صناعة",
    "erpPage.industries.description": "لدينا خبرة في تنفيذ ERPNext عبر قطاعات متنوعة مع تخصيصات خاصة بالصناعة.",
    "erpPage.industry.manufacturing": "التصنيع",
    "erpPage.industry.manufacturing.desc": "تخطيط الإنتاج وإدارة قائمة المواد ومراقبة الجودة وعمليات أرضية المصنع.",
    "erpPage.industry.manufacturing.f1": "إدارة أوامر العمل",
    "erpPage.industry.manufacturing.f2": "قائمة المواد",
    "erpPage.industry.manufacturing.f3": "فحص الجودة",
    "erpPage.industry.manufacturing.f4": "التعاقد من الباطن",
    "erpPage.industry.retail": "التجزئة والتجارة الإلكترونية",
    "erpPage.industry.retail.desc": "تكامل نقاط البيع وإدارة المخزون والمبيعات متعددة القنوات وبرامج ولاء العملاء.",
    "erpPage.industry.retail.f1": "نقاط البيع",
    "erpPage.industry.retail.f2": "تكامل التجارة الإلكترونية",
    "erpPage.industry.retail.f3": "برامج الولاء",
    "erpPage.industry.retail.f4": "المخزون متعدد المواقع",
    "erpPage.industry.logistics": "الخدمات اللوجستية والتوزيع",
    "erpPage.industry.logistics.desc": "إدارة المستودعات وتتبع الأسطول وتحسين التوصيل ورؤية سلسلة التوريد.",
    "erpPage.industry.logistics.f1": "إدارة المستودعات",
    "erpPage.industry.logistics.f2": "إدارة الأسطول",
    "erpPage.industry.logistics.f3": "تحسين المسارات",
    "erpPage.industry.logistics.f4": "التتبع في الوقت الفعلي",
    "erpPage.industry.services": "الخدمات المهنية",
    "erpPage.industry.services.desc": "إدارة المشاريع وتتبع الجداول الزمنية وتخصيص الموارد وفواتير العملاء.",
    "erpPage.industry.services.f1": "تتبع المشاريع",
    "erpPage.industry.services.f2": "إدارة الجداول الزمنية",
    "erpPage.industry.services.f3": "تخطيط الموارد",
    "erpPage.industry.services.f4": "بوابات العملاء",
    "erpPage.industry.healthcare": "الرعاية الصحية",
    "erpPage.industry.healthcare.desc": "إدارة المرضى وجدولة المواعيد ومخزون المستلزمات الطبية والامتثال.",
    "erpPage.industry.healthcare.f1": "سجلات المرضى",
    "erpPage.industry.healthcare.f2": "جدولة المواعيد",
    "erpPage.industry.healthcare.f3": "المخزون الطبي",
    "erpPage.industry.healthcare.f4": "تتبع الامتثال",
    "erpPage.industry.education": "التعليم",
    "erpPage.industry.education.desc": "أنظمة معلومات الطلاب وإدارة الرسوم وتخطيط الدورات والتتبع الأكاديمي.",
    "erpPage.industry.education.f1": "معلومات الطلاب",
    "erpPage.industry.education.f2": "إدارة الرسوم",
    "erpPage.industry.education.f3": "تخطيط الدورات",
    "erpPage.industry.education.f4": "التقارير الأكاديمية",
    "erpPage.cta.title": "هل أنت مستعد لتنفيذ ERPNext؟",
    "erpPage.cta.description": "دعنا نناقش كيف يمكن لـ ERPNext تبسيط عملياتك ودفع نمو الأعمال.",
    "erpPage.cta.button": "ابدأ رحلتك مع ERPNext",

    // Contact Page
    "contactPage.badge": "اتصل بنا",
    "contactPage.hero.title1": "لنبدأ رحلتك",
    "contactPage.hero.title2": "الرقمية",
    "contactPage.hero.description": "تواصل مع خبرائنا للحصول على استشارة مجانية واكتشف كيف يمكننا تحويل عملك.",
    "contactPage.form.title": "أرسل لنا رسالة",
    "contactPage.form.name": "الاسم الكامل",
    "contactPage.form.namePlaceholder": "محمد أحمد",
    "contactPage.form.email": "البريد الإلكتروني",
    "contactPage.form.emailPlaceholder": "mohammed@company.com",
    "contactPage.form.phone": "رقم الهاتف",
    "contactPage.form.phonePlaceholder": "+966 5XX XXX XXXX",
    "contactPage.form.company": "اسم الشركة",
    "contactPage.form.companyPlaceholder": "شركتك",
    "contactPage.form.service": "الخدمة المطلوبة",
    "contactPage.form.servicePlaceholder": "اختر خدمة",
    "contactPage.form.message": "رسالتك",
    "contactPage.form.messagePlaceholder": "أخبرنا عن متطلبات مشروعك...",
    "contactPage.form.submit": "إرسال الرسالة",
    "contactPage.form.submitting": "جاري الإرسال...",
    "contactPage.form.required": "*",
    "contactPage.info.title": "تواصل معنا",
    "contactPage.info.description": "هل لديك أسئلة؟ نحن هنا للمساعدة. تواصل معنا من خلال أي من القنوات أدناه.",
    "contactPage.info.phone": "الهاتف",
    "contactPage.info.email": "البريد الإلكتروني",
    "contactPage.info.hours": "ساعات العمل",
    "contactPage.info.hoursValue": "الأحد - الخميس: 9 ص - 6 م",
    "contactPage.expect.title": "ماذا تتوقع",
    "contactPage.expect.item1": "رد خلال 24 ساعة",
    "contactPage.expect.item2": "استشارة أولية مجانية",
    "contactPage.expect.item3": "اقتراح حل مخصص",
    "contactPage.expect.item4": "تسعير شفاف",
    "contactPage.services.erp": "تنفيذ ERP",
    "contactPage.services.crm": "حلول CRM",
    "contactPage.services.ai": "أتمتة الذكاء الاصطناعي",
    "contactPage.services.digital": "التحول الرقمي",
    "contactPage.services.governance": "الحوكمة المؤسسية",
    "contactPage.services.other": "أخرى",
    "contactPage.toast.title": "تم إرسال الرسالة بنجاح!",
"contactPage.toast.description": "شكرًا لتواصلك معنا. سيتواصل معك فريقنا خلال 24 ساعة.",
    "whatsapp.title": "تواصل بسرعة عبر واتساب",
    "whatsapp.subtitle": "فريقنا يرد خلال دقائق. أسرع طريقة لبدء مشروعك",
    "whatsapp.button": "ابدأ الدردشة على واتساب",
    "whatsapp.phone": "+966 58 314 0470",
  },

};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === "ar";

  useEffect(() => {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
